namespace: "pulp"
name: "squeezer"
authors:
  - "Matthias Dellweg <2500@gmx.de>"
  - "Timo Funke <timoses@msn.com>"
  - "Jacob Floyd <cognifloyd@gmail.com>"
  - "Yanis Guenane <yguenane@redhat.com>"
  - "Evgeni Golov <evgeni@golov.de>"
  - "Hamed Abdelli <abdelli.hamed@yahoo.fr>"
  - "Piotr Parczewski <piotr@stackhpc.com>"
  - "keilr <remy.keil@gmail.com>"
  - "Mark Goddard <mark@stackhpc.com>"
  - "Daniel Ziegenberg <daniel@ziegenberg.at>"
  - "Alex Welsh <alex@stackhpc.com>"
  - "ajsween <ajsween@gmail.com>"
version: "0.0.15-dev"
license_file: LICENSE
readme: README.md
repository: "https://github.com/pulp/squeezer"
tags:
  - infrastructure
  - pulp
