---
name: "Publish Release"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: "ubuntu-latest"
    if: "github.repository == 'pulp/squeezer'"
    steps:
      - uses: "actions/checkout@v7"
      - name: "Set up Python"
        uses: "actions/setup-python@v7"
        with:
          python-version: "3.13"
      - name: "Install Ansible"
        run: |
          pip install --upgrade ansible
      - name: "Build Ansible Collection"
        run: |
          make dist
      - name: "Publish Ansible Collection"
        run: |
          make publish GALAXY_API_KEY=${{ secrets.GALAXY_API_KEY }}
...
